# Site
name: "Davan Solutions"
title: "Davan Solutions"
description: "Join me on my journey to explore all new and old in the fabulous world of .NET"
logo: 'assets/images/Icon-512x512.png'
logo_full: 'assets/images/Logo_Neutral.png'
favicon: 'assets/images/favicon-32x32.png'
baseurl: /blog
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'davan-solutions-blog'
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: info@davan.solutions

# Authors
authors:
  davan:
    name: David Vanderheyden
    display_name: David Vanderheyden
    avatar: 'assets/images/Icon-512x512.png'
    email: info@davan.solutions
    linkedin: https://www.linkedin.com/in/david-vanderheyden/
    github: https://github.com/Cr3ature
    twitter: https://twitter.com/N1ghtCr3ature
    description: "Dad of 3, husband, .NET craftsman, Solution thinking #MicrosoftFanBoy #whoopThereItIs"
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
